### ISSUE TITLE
老哥还是写下wiki吧，🤣，感谢，借号神器

### ISSUE THREAD

**Issue by Boyuan26832** [Yukipedia/bilibili-joybook#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Yukipedia** [comment]
🤣我今天看看吧

**Comment by Boyuan26832** [comment]
> 🤣我今天看看吧

感谢，还挺好用的。就是可能第一眼不知道这个是干啥的🤣

**Comment by Yukipedia** [comment]
我也发现了这个问题😂

**Comment by Yukipedia** [comment]
> > 🤣我今天看看吧
> 
> 感谢，还挺好用的。就是可能第一眼不知道这个是干啥的🤣

我现在发现了这个问题😂

**Comment by Yukipedia** [comment]
做完了 🙃，这个 issue 还是挂着吧

**Comment by Boyuan26832** [comment]
> 做完了 🙃，这个 issue 还是挂着吧

哈哈哈，大佬流弊。
