### ISSUE TITLE
貌似已经失效了，播放界面显示未登录

### ISSUE THREAD

**Issue by RikkaBlue** [Yukipedia/bilibili-joybook#8]
用 chrome beta 和 yandex 正常和隐私模式（排除扩展干扰），均无法使用，播放界面会显示未登录。  
两个账号单独登录，账号状态正常。  
会有如下报错：
![](https://upload.cc/i1/2019/05/31/g86etz.png)

**Comment by PC6live** [comment]
🐴

**Comment by Yukipedia** [comment]
🦄失效已经了解，什么时候解决就不清楚了

**Comment by Boyuan26832** [comment]
> 🐴

这

**Comment by Boyuan26832** [comment]
> 🦄失效已经了解，什么时候解决就不清楚了

🌝🌝🌝

**Comment by Yukipedia** [comment]
今天测试了，大概算是知道如何解决白嫖失败原因，但因为个人时间原因，修复还要等几个星期左右。(还不一定行🦄
